version: "3"
services:
  sam:
    build:
      context: ./
      dockerfile: ./build/local/sam/Dockerfile
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - SAM_CLI_TELEMETRY=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src:/var/opt
    ports:
      - "3000:3000"
      - "5859:5858"
